import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Auth, ThemeSupa } from "@supabase/auth-ui-react";
import { useSession, useSupabaseClient } from "@supabase/auth-helpers-react";

export default function Home() {
  const session = useSession();
  const supabase = useSupabaseClient();
  return (
    <div className={styles.container}>
      <Head>
        <title>Comments</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="#">Mood</a>
        </h1>

        <div className={styles.grid}>
          {!session ? (
              // {<Auth
              //   supabaseClient={supabase}
              //   providers={["github"]}
              //   appearance={{ theme: ThemeSupa }}
              // />}
              <button onClick={() => supabase.auth.signInWithOAuth({ provider: "github" })}>Sign in with GitHub</button>
          ) : (
            <>
            <p>Logged in as {session.user.user_metadata.name}</p>
            <button onClick={() => supabase.auth.signOut()}>Sign out</button>
            </> 
          )}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}